# Cogitator: Dreadnought
#
# Profile for a NixOS EC2 instance deployed from a sarcophagus-aws AMI.
# Composes: ZFS, networking, impermanence, AWS platform, and the full hardening suite.
#
# The ZFS filesystem layout and GRUB boot loader are owned here because they are
# fully determined by the sarcophagus-aws AMI options (poolName, ebsDisk).
# The consumer's hardware-configuration.nix only needs to provide the
# instance-specific kernel modules generated by nixos-generate-config.
#
# Consumers add their own cogitators on top (traefik, docker-server, etc.)
# and provide a hardware-configuration.nix with the kernel modules section.
#
# Usage:
#   stc.cogitator.dreadnought.enable = true;
{
  config,
  lib,
  ...
}: let
  cfg = config.stc.cogitator.dreadnought;
in {
  imports = [
    ../../relics/nixos/zfs.nix
    ../../relics/nixos/networking.nix
    ../../relics/nixos/impermanence.nix
    ../../relics/nixos/aws.nix
    ./hardening.nix
  ];

  options.stc.cogitator.dreadnought = {
    enable = lib.mkEnableOption "NixOS EC2 running-system profile with ZFS + impermanence";

    poolName = lib.mkOption {
      type = lib.types.str;
      default = "vmpool";
      description = "ZFS pool name — must match the pool created by sarcophagus-aws.";
    };

    ebsDisk = lib.mkOption {
      type = lib.types.str;
      default = "nvme0n1";
      description = "EBS block device name (without /dev/). nvme0n1 for Nitro instances, xvda for Xen.";
    };

    ebsPartition = lib.mkOption {
      type = lib.types.int;
      default = 3;
      description = "Partition number holding the ZFS pool on the EBS disk.";
    };

    impermanence = {
      extraDirectories = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [];
        description = "Additional directories under /persist to bind-mount into /.";
      };

      extraFiles = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [];
        description = "Additional files under /persist to bind-mount into /.";
      };
    };
  };

  config = lib.mkIf cfg.enable {
    stc.relics.zfs.enable = true;
    stc.relics.networking.enable = true;
    stc.cogitator.hardening.enable = true;
    stc.relics.impermanence = {
      enable = true;
      inherit (cfg) poolName;
      inherit (cfg.impermanence) extraDirectories extraFiles;
    };
    stc.relics.aws = {
      enable = true;
      inherit (cfg) poolName;
      inherit (cfg) ebsDisk ebsPartition;
    };

    boot.loader.grub = {
      enable = true;
      device = "/dev/${cfg.ebsDisk}";
    };

    fileSystems."/" = {
      device = "${cfg.poolName}/root";
      fsType = "zfs";
      neededForBoot = true;
    };

    fileSystems."/nix" = {
      device = "${cfg.poolName}/nix";
      fsType = "zfs";
    };

    fileSystems."/persist" = {
      device = "${cfg.poolName}/persist";
      fsType = "zfs";
      neededForBoot = true;
    };

    fileSystems."/boot" = {
      device = "/dev/disk/by-label/ESP";
      fsType = "vfat";
    };
  };
}
